name: Pre-Push Action

on:
  push:
    branches:
      - master

jobs:
  check_scribe_file:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.1'

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Check if scribe.php exists
        run: |
          if [ -f config/scribe ]; then
            echo "scribe_file_exists=true"
          else
            echo "scribe_file_exists=false"
          fi
        id: check_file

      - name: Generate API documentation
        if: steps.check_file.outputs.scribe_file_exists == true
        run: php artisan scribe:generate

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Generate API documentation
          skip_fetch: true
